Updated readme to explain PHP CodeSniffer Autofix
stevegrunwell/wp-enforcer pull request #32
Opened 2017-03-13 21:54 UTC by bhubbard

2017-04-10 21:24 UTC, stevegrunwell requested changes
`phpcbf` is short for "PHP Code Beautifier and Fixer" — we should probably refer to it by its proper name. A sentence or two to describe the value of `phpcbf` (e.g. "PHP_CodeSniffer can fix many common indentation and formatting issues automatically, using the PHP Code Beautifier and Fixer (`phpcbf`) command:")

2017-04-13 17:29 UTC, bhubbard commented
@stevegrunwell Updated.

2017-04-13 18:09 UTC, stevegrunwell approved these changes

2017-04-13 18:09 UTC, merged

2017-04-13 18:09 UTC, stevegrunwell commented
@bhubbard Thank you!